directories:
  cache: "cache"
universal_import_line: "from manimlib import *"
window:
  position_string: UR
  monitor_index: 0
  full_screen: False
camera:
  resolution: (1920, 1080)
  background_color: "#000000"
  fps: 60
  background_opacity: 1.0
file_writer:
  saturation: 1.5
text:
  font: "CMU Serif"
  alignment: "CENTER"
tex:
  template: "default"
embed:
  autoreload: True
ignore_manimlib_modules_on_reload: True